#!/bin/bash
# MoAI PreTool Hook Wrapper - Generated by moai-adk-go
# This script forwards stdin JSON to the moai hook pre-tool command.
# Project-local hook: .claude/hooks/moai/pre-tool.sh

# Create temp file to store stdin
temp_file=$(mktemp)
trap 'rm -f "$temp_file"' EXIT

# Read stdin into temp file
cat > "$temp_file"

# Try moai command in PATH
if command -v moai &> /dev/null; then
	exec moai hook pre-tool < "$temp_file"
fi

# Try detected Go bin path from initialization
if [ -f "/root/go/bin/moai" ]; then
	exec "/root/go/bin/moai" hook pre-tool < "$temp_file"
fi

# Try default ~/go/bin/moai
if [ -f "/root/go/bin/moai" ]; then
	exec "/root/go/bin/moai" hook pre-tool < "$temp_file"
fi

# Not found - exit silently (Claude Code handles missing hooks gracefully)
exit 0
