/**
 * web_resources.c
 *
 * 웹 리소스를 C 문자열로 임베드 (자동 생성)
 * 수정하지 마세요! www/ 디렉토리의 원본 파일을 수정하세요.
 */

#include <stdint.h>
#include <stddef.h>

/* index.html */
const char index_html[] =
"<!DOCTYPE html>\n"
"<html lang=\"ko\">\n"
"<head>\n"
"    <meta charset=\"UTF-8\">\n"
"    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
"    <title>EoRa-S3 설정</title>\n"
"    <link rel=\"stylesheet\" href=\"/style.css\">\n"
"</head>\n"
"<body>\n"
"    <div class=\"container\">\n"
"        <header>\n"
"            <h1>EoRa-S3 네트워크 설정</h1>\n"
"            <div id=\"status-badge\" class=\"badge\">연결 중...</div>\n"
"        </header>\n"
"\n"
"        <!-- 네트워크 상태 -->\n"
"        <section class=\"card\">\n"
"            <h2>네트워크 상태</h2>\n"
"            <div class=\"status-grid\">\n"
"                <div class=\"status-item\">\n"
"                    <h3>WiFi AP</h3>\n"
"                    <div id=\"wifi-ap-status\">로딩 중...</div>\n"
"                </div>\n"
"                <div class=\"status-item\">\n"
"                    <h3>WiFi STA</h3>\n"
"                    <div id=\"wifi-sta-status\">로딩 중...</div>\n"
"                </div>\n"
"                <div class=\"status-item\">\n"
"                    <h3>Ethernet</h3>\n"
"                    <div id=\"eth-status\">로딩 중...</div>\n"
"                </div>\n"
"            </div>\n"
"        </section>\n"
"\n"
"        <!-- WiFi STA 설정 -->\n"
"        <section class=\"card\">\n"
"            <h2>WiFi STA 설정</h2>\n"
"            <div class=\"form-group\">\n"
"                <button id=\"wifi-scan-btn\" class=\"btn btn-secondary\">WiFi 네트워크 검색</button>\n"
"                <span id=\"wifi-scan-status\" style=\"margin-left: 10px;\"></span>\n"
"            </div>\n"
"            <div id=\"wifi-scan-results\" class=\"wifi-scan-results\" style=\"display: none;\">\n"
"                <!-- 스캔 결과가 여기에 동적으로 추가됨 -->\n"
"            </div>\n"
"            <form id=\"wifi-sta-form\">\n"
"                <div class=\"form-group\">\n"
"                    <label for=\"wifi-ssid\">SSID</label>\n"
"                    <input type=\"text\" id=\"wifi-ssid\" name=\"ssid\" required>\n"
"                </div>\n"
"                <div class=\"form-group\">\n"
"                    <label for=\"wifi-password\">비밀번호</label>\n"
"                    <input type=\"password\" id=\"wifi-password\" name=\"password\">\n"
"                </div>\n"
"                <button type=\"submit\" class=\"btn btn-primary\">저장</button>\n"
"            </form>\n"
"        </section>\n"
"\n"
"        <!-- Ethernet 설정 -->\n"
"        <section class=\"card\">\n"
"            <h2>Ethernet 설정</h2>\n"
"            <form id=\"eth-form\">\n"
"                <div class=\"form-group\">\n"
"                    <label>\n"
"                        <input type=\"checkbox\" id=\"eth-dhcp\" name=\"dhcp_enabled\">\n"
"                        DHCP 사용\n"
"                    </label>\n"
"                </div>\n"
"                <div id=\"eth-static-fields\">\n"
"                    <div class=\"form-group\">\n"
"                        <label for=\"eth-ip\">IP 주소</label>\n"
"                        <input type=\"text\" id=\"eth-ip\" name=\"static_ip\" pattern=\"\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}\">\n"
"                    </div>\n"
"                    <div class=\"form-group\">\n"
"                        <label for=\"eth-netmask\">넷마스크</label>\n"
"                        <input type=\"text\" id=\"eth-netmask\" name=\"static_netmask\" pattern=\"\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}\">\n"
"                    </div>\n"
"                    <div class=\"form-group\">\n"
"                        <label for=\"eth-gateway\">게이트웨이</label>\n"
"                        <input type=\"text\" id=\"eth-gateway\" name=\"static_gateway\" pattern=\"\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}\">\n"
"                    </div>\n"
"                </div>\n"
"                <button type=\"submit\" class=\"btn btn-primary\">저장</button>\n"
"            </form>\n"
"        </section>\n"
"\n"
"        <!-- 스위처 설정 -->\n"
"        <section class=\"card\">\n"
"            <h2>스위처 설정</h2>\n"
"\n"
"            <!-- 모드 선택 -->\n"
"            <div class=\"form-group\">\n"
"                <label for=\"switcher-mode-select\">동작 모드</label>\n"
"                <select id=\"switcher-mode-select\" class=\"mode-select\">\n"
"                    <option value=\"single\">싱글 모드 (Primary만)</option>\n"
"                    <option value=\"dual\">듀얼 모드 (Primary + Secondary)</option>\n"
"                </select>\n"
"                <button id=\"save-mode-btn\" class=\"btn btn-primary\" style=\"margin-left: 10px;\">모드 저장</button>\n"
"                <button id=\"restart-switcher-btn\" class=\"btn btn-warning\" style=\"margin-left: 10px;\">연결 재시작</button>\n"
"            </div>\n"
"\n"
"            <!-- 스위처 상태 요약 -->\n"
"            <div class=\"switcher-status-summary\">\n"
"                <div class=\"status-item\">\n"
"                    <h4>현재 모드</h4>\n"
"                    <div id=\"switcher-mode\" class=\"badge\">로딩 중...</div>\n"
"                </div>\n"
"                <div class=\"status-item\">\n"
"                    <h4>활성 스위처</h4>\n"
"                    <div id=\"switcher-active-count\">로딩 중...</div>\n"
"                </div>\n"
"            </div>\n"
"\n"
"            <div id=\"switcher-config\">\n"
"                <!-- Primary Switcher -->\n"
"                <div class=\"switcher-item\">\n"
"                    <h3>Primary Switcher\n"
"                        <span id=\"sw0-status-badge\" class=\"badge\">로딩 중...</span>\n"
"                    </h3>\n"
"                    <div id=\"sw0-connection-info\" class=\"connection-info\"></div>\n"
"                    <button class=\"btn btn-primary\" onclick=\"openSwitcherModal(0)\">설정</button>\n"
"                </div>\n"
"\n"
"                <!-- Secondary Switcher -->\n"
"                <div class=\"switcher-item\">\n"
"                    <h3>Secondary Switcher\n"
"                        <span id=\"sw1-status-badge\" class=\"badge\">로딩 중...</span>\n"
"                    </h3>\n"
"                    <div id=\"sw1-connection-info\" class=\"connection-info\"></div>\n"
"                    <button class=\"btn btn-primary\" onclick=\"openSwitcherModal(1)\">설정</button>\n"
"                </div>\n"
"            </div>\n"
"\n"
"            <!-- 카메라 매핑 비주얼 설정 -->\n"
"            <div class=\"mapping-visual-section\">\n"
"                <h3>카메라 번호 매핑</h3>\n"
"                <div class=\"mapping-info\">\n"
"                    <div class=\"info-item\">\n"
"                        <span class=\"color-box primary-color\"></span>\n"
"                        <span>Primary Switcher</span>\n"
"                    </div>\n"
"                    <div class=\"info-item\">\n"
"                        <span class=\"color-box secondary-color\"></span>\n"
"                        <span>Secondary Switcher</span>\n"
"                    </div>\n"
"                </div>\n"
"                <div class=\"camera-buttons\" id=\"camera-mapping-buttons\">\n"
"                    <!-- 버튼들은 JavaScript로 동적 생성 -->\n"
"                </div>\n"
"                <div class=\"mapping-controls\">\n"
"                    <p><strong>Secondary 시작 위치:</strong> <span id=\"secondary-start-pos\">-</span></p>\n"
"                    <button id=\"save-mapping-btn\" class=\"btn btn-primary\">매핑 저장</button>\n"
"                </div>\n"
"            </div>\n"
"        </section>\n"
"\n"
"        <!-- 시스템 상태 -->\n"
"        <section class=\"card\">\n"
"            <h2>시스템 상태</h2>\n"
"            <div class=\"health-grid\">\n"
"                <div class=\"health-item\">\n"
"                    <h3>전체 상태</h3>\n"
"                    <div id=\"health-overall\" class=\"health-value\">로딩 중...</div>\n"
"                </div>\n"
"                <div class=\"health-item\">\n"
"                    <h3>업타임</h3>\n"
"                    <div id=\"health-uptime\" class=\"health-value\">로딩 중...</div>\n"
"                </div>\n"
"                <div class=\"health-item\">\n"
"                    <h3>전압</h3>\n"
"                    <div id=\"health-voltage\" class=\"health-value\">로딩 중...</div>\n"
"                </div>\n"
"                <div class=\"health-item\">\n"
"                    <h3>배터리</h3>\n"
"                    <div id=\"health-battery\" class=\"health-value\">로딩 중...</div>\n"
"                </div>\n"
"                <div class=\"health-item\">\n"
"                    <h3>메모리</h3>\n"
"                    <div id=\"health-memory\" class=\"health-value\">로딩 중...</div>\n"
"                </div>\n"
"                <div class=\"health-item\">\n"
"                    <h3>온도</h3>\n"
"                    <div id=\"health-temperature\" class=\"health-value\">로딩 중...</div>\n"
"                </div>\n"
"                <div class=\"health-item\">\n"
"                    <h3>CPU 사용률</h3>\n"
"                    <div id=\"health-cpu\" class=\"health-value\">로딩 중...</div>\n"
"                </div>\n"
"            </div>\n"
"        </section>\n"
"\n"
"        <!-- LoRa 설정 -->\n"
"        <section class=\"card\">\n"
"            <h2>LoRa 통신 설정</h2>\n"
"\n"
"            <!-- LoRa 상태 -->\n"
"            <div class=\"lora-status-grid\">\n"
"                <div class=\"status-item\">\n"
"                    <h4>칩</h4>\n"
"                    <div id=\"lora-chip\" class=\"badge\">로딩 중...</div>\n"
"                </div>\n"
"                <div class=\"status-item\">\n"
"                    <h4>주파수</h4>\n"
"                    <div id=\"lora-frequency\">-</div>\n"
"                </div>\n"
"            </div>\n"
"\n"
"            <!-- 주파수 스캔 -->\n"
"            <div class=\"form-group\">\n"
"                <h3>주파수 채널 스캔</h3>\n"
"                <div style=\"margin-bottom: 10px; color: #666; font-size: 14px;\">\n"
"                    스캔 범위: <span id=\"scan-range-display\">-</span>\n"
"                </div>\n"
"                <div style=\"display: flex; gap: 10px; align-items: center; flex-wrap: wrap;\">\n"
"                    <button id=\"lora-scan-btn\" class=\"btn btn-secondary\">스캔 시작</button>\n"
"                    <span id=\"lora-scan-status\"></span>\n"
"                </div>\n"
"                <div id=\"lora-scan-results\" style=\"margin-top: 15px; display: none;\">\n"
"                    <h4>스캔 결과</h4>\n"
"                    <div id=\"lora-scan-chart\" class=\"scan-chart\"></div>\n"
"                </div>\n"
"            </div>\n"
"\n"
"            <!-- 주파수 변경 -->\n"
"            <div class=\"form-group\">\n"
"                <h3>주파수 설정 (임시)</h3>\n"
"                <div style=\"display: flex; gap: 10px; align-items: center;\">\n"
"                    <label for=\"lora-freq-input\">주파수 (MHz):</label>\n"
"                    <input type=\"number\" id=\"lora-freq-input\" step=\"0.1\" style=\"width: 100px;\">\n"
"                    <button id=\"lora-freq-save-btn\" class=\"btn btn-secondary\">임시 저장</button>\n"
"                    <span id=\"freq-pending-badge\" style=\"display:none; color: orange; font-size: 20px;\">●</span>\n"
"                </div>\n"
"                <small id=\"freq-range-hint\" style=\"color: #666;\">-</small>\n"
"            </div>\n"
"\n"
"            <!-- Sync Word 변경 -->\n"
"            <div class=\"form-group\">\n"
"                <h3>Sync Word 설정 (임시)</h3>\n"
"                <div style=\"display: flex; gap: 10px; align-items: center;\">\n"
"                    <label for=\"lora-sync-input\">Sync Word:</label>\n"
"                    <input type=\"range\" id=\"lora-sync-input\" min=\"0\" max=\"255\" value=\"18\" style=\"flex: 1; max-width: 300px;\">\n"
"                    <span id=\"lora-sync-value\" style=\"font-weight: bold; min-width: 60px;\">0x12</span>\n"
"                    <button id=\"lora-sync-save-btn\" class=\"btn btn-secondary\">임시 저장</button>\n"
"                    <span id=\"sync-pending-badge\" style=\"display:none; color: orange; font-size: 20px;\">●</span>\n"
"                </div>\n"
"                <small style=\"color: #666;\">같은 Sync Word를 가진 장치끼리만 통신 가능 (네트워크 분리, 0x00~0xFF)</small>\n"
"            </div>\n"
"\n"
"            <!-- 설정 적용 -->\n"
"            <div class=\"form-group\" style=\"margin-top: 25px; padding: 20px; background: #fff3cd; border: 2px solid #ffc107; border-radius: 8px;\">\n"
"                <h3 style=\"margin-top: 0;\">⚠️ 설정 적용</h3>\n"
"                <p style=\"margin: 10px 0; color: #856404; line-height: 1.6;\">\n"
"                    위에서 임시 저장한 설정을 실제로 적용합니다.<br>\n"
"                    <strong>RX 장치에 3회 알림을 보낸 후 TX도 변경됩니다.</strong><br>\n"
"                    <small>(총 소요 시간: 약 4초)</small>\n"
"                </p>\n"
"                <button id=\"lora-apply-btn\" class=\"btn btn-primary\" style=\"font-size: 16px; padding: 12px 24px;\">\n"
"                    설정 적용하기\n"
"                </button>\n"
"                <div id=\"lora-apply-status\" style=\"margin-top: 15px; font-weight: bold;\"></div>\n"
"            </div>\n"
"        </section>\n"
"\n"
"        <!-- 시스템 제어 -->\n"
"        <section class=\"card\">\n"
"            <h2>시스템 제어</h2>\n"
"            <button id=\"restart-btn\" class=\"btn btn-danger\">시스템 재시작</button>\n"
"        </section>\n"
"\n"
"        <footer>\n"
"            <p>EoRa-S3 Firmware v1.0</p>\n"
"        </footer>\n"
"    </div>\n"
"\n"
"    <!-- 스위처 설정 모달 -->\n"
"    <div id=\"switcher-modal\" class=\"modal\">\n"
"        <div class=\"modal-content\">\n"
"            <div class=\"modal-header\">\n"
"                <h2 id=\"modal-title\">스위처 설정</h2>\n"
"                <span class=\"modal-close\" onclick=\"closeSwitcherModal()\">&times;</span>\n"
"            </div>\n"
"            <div class=\"modal-body\">\n"
"                <form id=\"modal-switcher-form\">\n"
"                    <input type=\"hidden\" id=\"modal-index\" value=\"0\">\n"
"\n"
"                    <div class=\"form-group\">\n"
"                        <label for=\"modal-type\">타입</label>\n"
"                        <select id=\"modal-type\" name=\"type\">\n"
"                            <option value=\"1\">ATEM</option>\n"
"                            <option value=\"2\">vMix</option>\n"
"                            <option value=\"3\">OBS</option>\n"
"                        </select>\n"
"                    </div>\n"
"\n"
"                    <div class=\"form-group\">\n"
"                        <label for=\"modal-interface\">통신 방식</label>\n"
"                        <select id=\"modal-interface\" name=\"interface\">\n"
"                            <option value=\"1\">WiFi STA</option>\n"
"                            <option value=\"2\">Ethernet</option>\n"
"                        </select>\n"
"                    </div>\n"
"\n"
"                    <div class=\"form-group\">\n"
"                        <label for=\"modal-ip\">IP 주소</label>\n"
"                        <input type=\"text\" id=\"modal-ip\" name=\"ip\" pattern=\"\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}\" required>\n"
"                    </div>\n"
"\n"
"                    <div class=\"form-group\" id=\"modal-password-group\">\n"
"                        <label for=\"modal-password\">비밀번호</label>\n"
"                        <input type=\"password\" id=\"modal-password\" name=\"password\">\n"
"                    </div>\n"
"\n"
"                    <div class=\"form-group\">\n"
"                        <label for=\"modal-camera-limit\">Camera Limit (0=자동)</label>\n"
"                        <input type=\"number\" id=\"modal-camera-limit\" name=\"camera_limit\" min=\"0\" max=\"20\" value=\"0\">\n"
"                        <small style=\"color: #666;\">카메라 개수 제한 (0=자동 감지)</small>\n"
"                    </div>\n"
"                </form>\n"
"            </div>\n"
"            <div class=\"modal-footer\">\n"
"                <button id=\"modal-save-btn\" class=\"btn btn-primary\">저장</button>\n"
"            </div>\n"
"        </div>\n"
"    </div>\n"
"\n"
"    <!-- 토스트 메시지 컨테이너 -->\n"
"    <div id=\"toast-container\" class=\"toast-container\"></div>\n"
"\n"
"    <script src=\"/app.js\"></script>\n"
"</body>\n"
"</html>\n"
"\n";

const size_t index_html_len = sizeof(index_html) - 1;

/* style.css */
const char style_css[] =
"* {\n"
"    margin: 0;\n"
"    padding: 0;\n"
"    box-sizing: border-box;\n"
"}\n"
"\n"
"body {\n"
"    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Arial, sans-serif;\n"
"    background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);\n"
"    min-height: 100vh;\n"
"    padding: 20px;\n"
"}\n"
"\n"
".container {\n"
"    max-width: 800px;\n"
"    margin: 0 auto;\n"
"}\n"
"\n"
"header {\n"
"    background: white;\n"
"    padding: 20px;\n"
"    border-radius: 10px;\n"
"    margin-bottom: 20px;\n"
"    display: flex;\n"
"    justify-content: space-between;\n"
"    align-items: center;\n"
"    box-shadow: 0 2px 10px rgba(0,0,0,0.1);\n"
"}\n"
"\n"
"header h1 {\n"
"    color: #333;\n"
"    font-size: 24px;\n"
"}\n"
"\n"
".badge {\n"
"    padding: 8px 16px;\n"
"    border-radius: 20px;\n"
"    font-size: 14px;\n"
"    font-weight: 600;\n"
"}\n"
"\n"
".badge.connected {\n"
"    background: #10b981;\n"
"    color: white;\n"
"}\n"
"\n"
".badge.connecting {\n"
"    background: #f59e0b;\n"
"    color: white;\n"
"}\n"
"\n"
".card {\n"
"    background: white;\n"
"    padding: 24px;\n"
"    border-radius: 10px;\n"
"    margin-bottom: 20px;\n"
"    box-shadow: 0 2px 10px rgba(0,0,0,0.1);\n"
"}\n"
"\n"
".card h2 {\n"
"    color: #333;\n"
"    font-size: 20px;\n"
"    margin-bottom: 20px;\n"
"    padding-bottom: 10px;\n"
"    border-bottom: 2px solid #f3f4f6;\n"
"}\n"
"\n"
".status-grid {\n"
"    display: grid;\n"
"    grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));\n"
"    gap: 16px;\n"
"}\n"
"\n"
".status-item {\n"
"    padding: 16px;\n"
"    background: #f9fafb;\n"
"    border-radius: 8px;\n"
"    border-left: 4px solid #667eea;\n"
"}\n"
"\n"
".status-item h3 {\n"
"    color: #667eea;\n"
"    font-size: 14px;\n"
"    margin-bottom: 8px;\n"
"    text-transform: uppercase;\n"
"    letter-spacing: 0.5px;\n"
"}\n"
"\n"
".status-item .value {\n"
"    color: #333;\n"
"    font-size: 16px;\n"
"    margin: 4px 0;\n"
"}\n"
"\n"
".status-item .label {\n"
"    color: #6b7280;\n"
"    font-size: 12px;\n"
"}\n"
"\n"
".form-group {\n"
"    margin-bottom: 16px;\n"
"}\n"
"\n"
".form-group label {\n"
"    display: block;\n"
"    color: #374151;\n"
"    font-weight: 500;\n"
"    margin-bottom: 6px;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
".form-group input[type=\"text\"],\n"
".form-group input[type=\"password\"] {\n"
"    width: 100%;\n"
"    padding: 10px 12px;\n"
"    border: 2px solid #e5e7eb;\n"
"    border-radius: 6px;\n"
"    font-size: 14px;\n"
"    transition: border-color 0.2s;\n"
"}\n"
"\n"
".form-group input[type=\"text\"]:focus,\n"
".form-group input[type=\"password\"]:focus {\n"
"    outline: none;\n"
"    border-color: #667eea;\n"
"}\n"
"\n"
".form-group input[type=\"checkbox\"] {\n"
"    margin-right: 8px;\n"
"    width: 18px;\n"
"    height: 18px;\n"
"    cursor: pointer;\n"
"}\n"
"\n"
".btn {\n"
"    padding: 10px 20px;\n"
"    border: none;\n"
"    border-radius: 6px;\n"
"    font-size: 14px;\n"
"    font-weight: 600;\n"
"    cursor: pointer;\n"
"    transition: all 0.2s;\n"
"}\n"
"\n"
".btn-primary {\n"
"    background: #667eea;\n"
"    color: white;\n"
"}\n"
"\n"
".btn-primary:hover {\n"
"    background: #5568d3;\n"
"    transform: translateY(-1px);\n"
"    box-shadow: 0 4px 12px rgba(102, 126, 234, 0.4);\n"
"}\n"
"\n"
".btn-danger {\n"
"    background: #ef4444;\n"
"    color: white;\n"
"}\n"
"\n"
".btn-danger:hover {\n"
"    background: #dc2626;\n"
"    transform: translateY(-1px);\n"
"    box-shadow: 0 4px 12px rgba(239, 68, 68, 0.4);\n"
"}\n"
"\n"
".btn:disabled {\n"
"    opacity: 0.5;\n"
"    cursor: not-allowed;\n"
"}\n"
"\n"
"#eth-static-fields {\n"
"    margin-top: 16px;\n"
"}\n"
"\n"
"/* Health 상태 그리드 */\n"
".health-grid {\n"
"    display: grid;\n"
"    grid-template-columns: repeat(auto-fit, minmax(180px, 1fr));\n"
"    gap: 16px;\n"
"}\n"
"\n"
".health-item {\n"
"    padding: 16px;\n"
"    background: #f9fafb;\n"
"    border-radius: 8px;\n"
"    text-align: center;\n"
"    border: 2px solid #e5e7eb;\n"
"    transition: all 0.3s ease;\n"
"}\n"
"\n"
".health-item:hover {\n"
"    box-shadow: 0 4px 12px rgba(0,0,0,0.1);\n"
"    transform: translateY(-2px);\n"
"}\n"
"\n"
".health-item h3 {\n"
"    color: #6b7280;\n"
"    font-size: 13px;\n"
"    margin-bottom: 10px;\n"
"    text-transform: uppercase;\n"
"    letter-spacing: 0.5px;\n"
"    font-weight: 600;\n"
"}\n"
"\n"
".health-value {\n"
"    color: #333;\n"
"    font-size: 20px;\n"
"    font-weight: 700;\n"
"    margin-bottom: 4px;\n"
"}\n"
"\n"
".health-value.status-ok {\n"
"    color: #10b981;\n"
"}\n"
"\n"
".health-value.status-warning {\n"
"    color: #f59e0b;\n"
"}\n"
"\n"
".health-value.status-critical {\n"
"    color: #ef4444;\n"
"}\n"
"\n"
".health-value.status-unavailable {\n"
"    color: #9ca3af;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"footer {\n"
"    text-align: center;\n"
"    color: white;\n"
"    padding: 20px;\n"
"    font-size: 14px;\n"
"    opacity: 0.8;\n"
"}\n"
"\n"
".message {\n"
"    padding: 12px 16px;\n"
"    border-radius: 6px;\n"
"    margin-bottom: 16px;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
".message.success {\n"
"    background: #d1fae5;\n"
"    color: #065f46;\n"
"    border: 1px solid #10b981;\n"
"}\n"
"\n"
".message.error {\n"
"    background: #fee2e2;\n"
"    color: #991b1b;\n"
"    border: 1px solid #ef4444;\n"
"}\n"
"\n"
"/* 토스트 메시지 */\n"
".toast-container {\n"
"    position: fixed;\n"
"    bottom: 20px;\n"
"    left: 50%;\n"
"    transform: translateX(-50%);\n"
"    z-index: 1000;\n"
"    display: flex;\n"
"    flex-direction: column;\n"
"    gap: 10px;\n"
"    min-width: 300px;\n"
"    max-width: 500px;\n"
"}\n"
"\n"
".toast {\n"
"    padding: 16px 20px;\n"
"    border-radius: 8px;\n"
"    box-shadow: 0 4px 12px rgba(0, 0, 0, 0.15);\n"
"    font-size: 14px;\n"
"    font-weight: 500;\n"
"    animation: slideUp 0.3s ease-out;\n"
"    display: flex;\n"
"    align-items: center;\n"
"    gap: 10px;\n"
"}\n"
"\n"
".toast.success {\n"
"    background: #10b981;\n"
"    color: white;\n"
"}\n"
"\n"
".toast.error {\n"
"    background: #ef4444;\n"
"    color: white;\n"
"}\n"
"\n"
".toast.info {\n"
"    background: #3b82f6;\n"
"    color: white;\n"
"}\n"
"\n"
".toast.warning {\n"
"    background: #f59e0b;\n"
"    color: white;\n"
"}\n"
"\n"
"@keyframes slideUp {\n"
"    from {\n"
"        transform: translateY(100px);\n"
"        opacity: 0;\n"
"    }\n"
"    to {\n"
"        transform: translateY(0);\n"
"        opacity: 1;\n"
"    }\n"
"}\n"
"\n"
"@keyframes slideDown {\n"
"    from {\n"
"        transform: translateY(0);\n"
"        opacity: 1;\n"
"    }\n"
"    to {\n"
"        transform: translateY(100px);\n"
"        opacity: 0;\n"
"    }\n"
"}\n"
"\n"
".toast.hiding {\n"
"    animation: slideDown 0.3s ease-in forwards;\n"
"}\n"
"\n"
"/* 반응형 */\n"
"/* 스위처 설정 */\n"
"/* 스위처 상태 요약 */\n"
".switcher-status-summary {\n"
"    display: grid;\n"
"    grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));\n"
"    gap: 15px;\n"
"    margin-bottom: 20px;\n"
"    padding: 15px;\n"
"    background: #f9fafb;\n"
"    border-radius: 8px;\n"
"    border: 1px solid #e5e7eb;\n"
"}\n"
"\n"
".switcher-status-summary .status-item {\n"
"    text-align: center;\n"
"}\n"
"\n"
".switcher-status-summary h4 {\n"
"    color: #6b7280;\n"
"    font-size: 12px;\n"
"    font-weight: 500;\n"
"    margin-bottom: 8px;\n"
"    text-transform: uppercase;\n"
"}\n"
"\n"
".switcher-status-summary .badge {\n"
"    display: inline-block;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"/* 스위처 아이템 */\n"
".switcher-item {\n"
"    background: #f9fafb;\n"
"    padding: 20px;\n"
"    border-radius: 8px;\n"
"    margin-bottom: 20px;\n"
"    border: 1px solid #e5e7eb;\n"
"}\n"
"\n"
".switcher-item h3 {\n"
"    color: #374151;\n"
"    margin-bottom: 15px;\n"
"    font-size: 16px;\n"
"    font-weight: 600;\n"
"    display: flex;\n"
"    align-items: center;\n"
"    justify-content: space-between;\n"
"}\n"
"\n"
".switcher-item h3 .badge {\n"
"    font-size: 12px;\n"
"    padding: 4px 12px;\n"
"}\n"
"\n"
"/* 연결 정보 */\n"
".connection-info {\n"
"    margin-bottom: 15px;\n"
"    padding: 10px;\n"
"    background: white;\n"
"    border-radius: 6px;\n"
"    border-left: 3px solid #10b981;\n"
"}\n"
"\n"
".connection-info .label {\n"
"    color: #4b5563;\n"
"    font-size: 13px;\n"
"}\n"
"\n"
"/* 카메라 매핑 비주얼 섹션 */\n"
".mapping-visual-section {\n"
"    background: #f9fafb;\n"
"    padding: 20px;\n"
"    border-radius: 8px;\n"
"    margin-top: 20px;\n"
"    border: 1px solid #e5e7eb;\n"
"}\n"
"\n"
".mapping-visual-section h3 {\n"
"    color: #374151;\n"
"    margin-bottom: 15px;\n"
"    font-size: 16px;\n"
"    font-weight: 600;\n"
"}\n"
"\n"
".mapping-info {\n"
"    display: flex;\n"
"    gap: 20px;\n"
"    margin-bottom: 15px;\n"
"    padding: 10px;\n"
"    background: white;\n"
"    border-radius: 6px;\n"
"}\n"
"\n"
".info-item {\n"
"    display: flex;\n"
"    align-items: center;\n"
"    gap: 8px;\n"
"    font-size: 14px;\n"
"    color: #374151;\n"
"}\n"
"\n"
".color-box {\n"
"    width: 24px;\n"
"    height: 24px;\n"
"    border-radius: 4px;\n"
"    border: 2px solid #e5e7eb;\n"
"}\n"
"\n"
".primary-color {\n"
"    background: #ef4444;\n"
"}\n"
"\n"
".secondary-color {\n"
"    background: #3b82f6;\n"
"}\n"
"\n"
".camera-buttons {\n"
"    display: flex;\n"
"    flex-wrap: wrap;\n"
"    gap: 8px;\n"
"    margin: 15px 0;\n"
"    padding: 15px;\n"
"    background: white;\n"
"    border-radius: 6px;\n"
"    min-height: 80px;\n"
"}\n"
"\n"
".camera-btn {\n"
"    width: 50px;\n"
"    height: 50px;\n"
"    border: 2px solid #e5e7eb;\n"
"    border-radius: 6px;\n"
"    background: white;\n"
"    color: #374151;\n"
"    font-size: 14px;\n"
"    font-weight: 600;\n"
"    cursor: pointer;\n"
"    transition: all 0.2s;\n"
"    display: flex;\n"
"    align-items: center;\n"
"    justify-content: center;\n"
"}\n"
"\n"
".camera-btn:hover {\n"
"    border-color: #667eea;\n"
"    transform: translateY(-2px);\n"
"    box-shadow: 0 4px 8px rgba(0,0,0,0.1);\n"
"}\n"
"\n"
".camera-btn.primary {\n"
"    background: #ef4444;\n"
"    color: white;\n"
"    border-color: #dc2626;\n"
"}\n"
"\n"
".camera-btn.secondary {\n"
"    background: #3b82f6;\n"
"    color: white;\n"
"    border-color: #2563eb;\n"
"}\n"
"\n"
"/* Secondary 선택 가능 영역 (파란색 반투명) */\n"
".camera-btn.selectable-secondary {\n"
"    background: rgba(59, 130, 246, 0.2);\n"
"    color: #3b82f6;\n"
"    border-color: #93c5fd;\n"
"    border-style: dashed;\n"
"}\n"
"\n"
"/* 선택된 버튼 (진한 파란색) */\n"
".camera-btn.selected {\n"
"    background: #1e40af !important;\n"
"    color: white !important;\n"
"    border-color: #1e3a8a !important;\n"
"    border-width: 3px !important;\n"
"    border-style: solid !important;\n"
"    box-shadow: 0 0 12px rgba(30, 64, 175, 0.6);\n"
"}\n"
"\n"
".camera-btn.clickable {\n"
"    cursor: pointer;\n"
"}\n"
"\n"
".camera-btn.clickable:hover {\n"
"    border-color: #3b82f6;\n"
"    border-width: 3px;\n"
"}\n"
"\n"
".camera-btn.selectable-secondary:hover {\n"
"    background: rgba(59, 130, 246, 0.3);\n"
"    border-style: solid;\n"
"}\n"
"\n"
".mapping-controls {\n"
"    margin-top: 15px;\n"
"    padding: 15px;\n"
"    background: white;\n"
"    border-radius: 6px;\n"
"    display: flex;\n"
"    justify-content: space-between;\n"
"    align-items: center;\n"
"}\n"
"\n"
".mapping-controls p {\n"
"    margin: 0;\n"
"    color: #374151;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
".mapping-controls span {\n"
"    color: #667eea;\n"
"    font-weight: 700;\n"
"    font-size: 16px;\n"
"}\n"
"\n"
".form-group input[type=\"number\"] {\n"
"    width: 100%;\n"
"    padding: 10px 12px;\n"
"    border: 2px solid #e5e7eb;\n"
"    border-radius: 6px;\n"
"    font-size: 14px;\n"
"    transition: border-color 0.2s;\n"
"}\n"
"\n"
".form-group input[type=\"number\"]:focus {\n"
"    outline: none;\n"
"    border-color: #667eea;\n"
"}\n"
"\n"
".form-group select {\n"
"    width: 100%;\n"
"    padding: 10px 12px;\n"
"    border: 2px solid #e5e7eb;\n"
"    border-radius: 6px;\n"
"    font-size: 14px;\n"
"    background-color: white;\n"
"    cursor: pointer;\n"
"    transition: border-color 0.2s;\n"
"}\n"
"\n"
".form-group select:focus {\n"
"    outline: none;\n"
"    border-color: #667eea;\n"
"}\n"
"\n"
".form-group small {\n"
"    display: block;\n"
"    color: #6b7280;\n"
"    font-size: 12px;\n"
"    margin-top: 4px;\n"
"}\n"
"\n"
".info-text {\n"
"    color: #667eea;\n"
"    font-weight: 600;\n"
"    font-size: 16px;\n"
"}\n"
"\n"
".btn-secondary {\n"
"    background: #6b7280;\n"
"    color: white;\n"
"}\n"
"\n"
".btn-secondary:hover {\n"
"    background: #4b5563;\n"
"    transform: translateY(-1px);\n"
"    box-shadow: 0 4px 12px rgba(107, 114, 128, 0.4);\n"
"}\n"
"\n"
"/* 모달 */\n"
".modal {\n"
"    display: none;\n"
"    position: fixed;\n"
"    z-index: 1000;\n"
"    left: 0;\n"
"    top: 0;\n"
"    width: 100%;\n"
"    height: 100%;\n"
"    background-color: rgba(0, 0, 0, 0.5);\n"
"    animation: fadeIn 0.3s ease-out;\n"
"}\n"
"\n"
".modal.show {\n"
"    display: flex;\n"
"    align-items: center;\n"
"    justify-content: center;\n"
"}\n"
"\n"
".modal-content {\n"
"    background: white;\n"
"    border-radius: 12px;\n"
"    max-width: 500px;\n"
"    width: 90%;\n"
"    max-height: 90vh;\n"
"    overflow-y: auto;\n"
"    box-shadow: 0 10px 40px rgba(0, 0, 0, 0.3);\n"
"    animation: slideDown 0.3s ease-out;\n"
"}\n"
"\n"
".modal-header {\n"
"    padding: 20px 24px;\n"
"    border-bottom: 2px solid #f3f4f6;\n"
"    display: flex;\n"
"    justify-content: space-between;\n"
"    align-items: center;\n"
"}\n"
"\n"
".modal-header h2 {\n"
"    color: #333;\n"
"    font-size: 20px;\n"
"    margin: 0;\n"
"}\n"
"\n"
".modal-close {\n"
"    font-size: 28px;\n"
"    color: #6b7280;\n"
"    cursor: pointer;\n"
"    line-height: 1;\n"
"    transition: color 0.2s;\n"
"}\n"
"\n"
".modal-close:hover {\n"
"    color: #ef4444;\n"
"}\n"
"\n"
".modal-body {\n"
"    padding: 24px;\n"
"}\n"
"\n"
".modal-footer {\n"
"    padding: 16px 24px;\n"
"    border-top: 2px solid #f3f4f6;\n"
"    display: flex;\n"
"    gap: 10px;\n"
"    justify-content: flex-end;\n"
"}\n"
"\n"
"@keyframes fadeIn {\n"
"    from {\n"
"        opacity: 0;\n"
"    }\n"
"    to {\n"
"        opacity: 1;\n"
"    }\n"
"}\n"
"\n"
"@keyframes slideDown {\n"
"    from {\n"
"        transform: translateY(-50px);\n"
"        opacity: 0;\n"
"    }\n"
"    to {\n"
"        transform: translateY(0);\n"
"        opacity: 1;\n"
"    }\n"
"}\n"
"\n"
".btn-warning {\n"
"    background: #f59e0b;\n"
"    color: white;\n"
"}\n"
"\n"
".btn-warning:hover {\n"
"    background: #d97706;\n"
"    transform: translateY(-1px);\n"
"    box-shadow: 0 4px 12px rgba(245, 158, 11, 0.4);\n"
"}\n"
"\n"
"@media (max-width: 640px) {\n"
"    .status-grid {\n"
"        grid-template-columns: 1fr;\n"
"    }\n"
"\n"
"    header {\n"
"        flex-direction: column;\n"
"        gap: 12px;\n"
"        text-align: center;\n"
"    }\n"
"\n"
"    .toast-container {\n"
"        min-width: calc(100% - 40px);\n"
"        max-width: calc(100% - 40px);\n"
"    }\n"
"\n"
"    .modal-content {\n"
"        width: 95%;\n"
"        max-height: 95vh;\n"
"    }\n"
"\n"
"    .modal-footer {\n"
"        flex-direction: column;\n"
"    }\n"
"\n"
"    .modal-footer .btn {\n"
"        width: 100%;\n"
"    }\n"
"}\n"
"\n"
"/* WiFi 스캔 결과 */\n"
".wifi-scan-results {\n"
"    margin: 15px 0;\n"
"    max-height: 400px;\n"
"    overflow-y: auto;\n"
"    border: 1px solid #e5e7eb;\n"
"    border-radius: 8px;\n"
"    background: #f9fafb;\n"
"}\n"
"\n"
".wifi-network-item {\n"
"    padding: 12px 15px;\n"
"    border-bottom: 1px solid #e5e7eb;\n"
"    cursor: pointer;\n"
"    transition: background 0.2s;\n"
"}\n"
"\n"
".wifi-network-item:last-child {\n"
"    border-bottom: none;\n"
"}\n"
"\n"
".wifi-network-item:hover {\n"
"    background: #e5e7eb;\n"
"}\n"
"\n"
".network-info {\n"
"    display: flex;\n"
"    justify-content: space-between;\n"
"    align-items: center;\n"
"    margin-bottom: 5px;\n"
"}\n"
"\n"
".network-info strong {\n"
"    color: #333;\n"
"    font-size: 15px;\n"
"}\n"
"\n"
".network-auth {\n"
"    padding: 2px 8px;\n"
"    background: #667eea;\n"
"    color: white;\n"
"    border-radius: 4px;\n"
"    font-size: 12px;\n"
"}\n"
"\n"
".network-details {\n"
"    display: flex;\n"
"    gap: 15px;\n"
"    font-size: 13px;\n"
"    color: #666;\n"
"}\n"
"\n"
"/* LoRa 설정 스타일 */\n"
".lora-status-grid {\n"
"    display: grid;\n"
"    grid-template-columns: repeat(auto-fit, minmax(150px, 1fr));\n"
"    gap: 15px;\n"
"    margin-bottom: 25px;\n"
"}\n"
"\n"
".lora-status-grid .status-item {\n"
"    text-align: center;\n"
"}\n"
"\n"
".lora-status-grid h4 {\n"
"    font-size: 12px;\n"
"    color: #666;\n"
"    margin-bottom: 5px;\n"
"}\n"
"\n"
".scan-chart {\n"
"    background: #f9fafb;\n"
"    padding: 15px;\n"
"    border-radius: 8px;\n"
"    border: 1px solid #e5e7eb;\n"
"}\n"
"\n";

const size_t style_css_len = sizeof(style_css) - 1;

/* app.js */
const char app_js[] =
"// API 엔드포인트\n"
"const API = {\n"
"    STATUS: '/api/status',\n"
"    CONFIG: '/api/config',\n"
"    WIFI: '/api/config/wifi',\n"
"    WIFI_SCAN: '/api/wifi/scan',\n"
"    ETH: '/api/config/eth',\n"
"    SWITCHERS: '/api/config/switchers',\n"
"    SWITCHER: '/api/config/switcher',\n"
"    SWITCHER_MAPPING: '/api/config/switcher/mapping',\n"
"    MODE: '/api/config/mode',\n"
"    HEALTH: '/api/system/health',\n"
"    RESTART: '/api/restart',\n"
"    SWITCHER_RESTART: '/api/switcher/restart',\n"
"    LORA_STATUS: '/api/lora/status',\n"
"    LORA_SCAN: '/api/lora/scan',\n"
"    LORA_CONFIG: '/api/lora/config'\n"
"};\n"
"\n"
"// 상태 업데이트 주기 (ms)\n"
"const UPDATE_INTERVAL = 3000;\n"
"const HEALTH_UPDATE_INTERVAL = 5000;\n"
"\n"
"// 전역 변수\n"
"let updateTimer = null;\n"
"let healthTimer = null;\n"
"let switcherData = null;  // API 로드 전까지 null\n"
"let secondaryStartPos = 1;\n"
"\n"
"// 초기화\n"
"document.addEventListener('DOMContentLoaded', () => {\n"
"    console.log('EoRa-S3 Web UI 초기화...');\n"
"\n"
"    // 초기 데이터 로드\n"
"    loadConfig();\n"
"    loadSwitcherConfig();\n"
"    updateStatus();\n"
"    updateHealth();\n"
"    updateLoRaStatus();\n"
"\n"
"    // 주기적 상태 업데이트\n"
"    updateTimer = setInterval(updateStatus, UPDATE_INTERVAL);\n"
"    healthTimer = setInterval(updateHealth, HEALTH_UPDATE_INTERVAL);\n"
"\n"
"    // 이벤트 리스너 등록\n"
"    setupEventListeners();\n"
"});\n"
"\n"
"// 이벤트 리스너 설정\n"
"function setupEventListeners() {\n"
"    // WiFi 스캔 버튼\n"
"    document.getElementById('wifi-scan-btn').addEventListener('click', handleWiFiScan);\n"
"\n"
"    // WiFi STA 폼\n"
"    document.getElementById('wifi-sta-form').addEventListener('submit', handleWiFiSubmit);\n"
"\n"
"    // Ethernet 폼\n"
"    document.getElementById('eth-form').addEventListener('submit', handleEthSubmit);\n"
"\n"
"    // 모드 저장 버튼\n"
"    document.getElementById('save-mode-btn').addEventListener('click', handleModeChange);\n"
"\n"
"    // 스위처 연결 재시작 버튼\n"
"    document.getElementById('restart-switcher-btn').addEventListener('click', handleSwitcherRestart);\n"
"\n"
"    // 매핑 저장 버튼\n"
"    document.getElementById('save-mapping-btn').addEventListener('click', handleMappingSave);\n"
"\n"
"    // 재시작 버튼\n"
"    document.getElementById('restart-btn').addEventListener('click', handleRestart);\n"
"\n"
"    // LoRa 스캔 버튼\n"
"    document.getElementById('lora-scan-btn').addEventListener('click', handleLoRaScan);\n"
"\n"
"    // LoRa 주파수 변경 버튼\n"
"    document.getElementById('lora-freq-save-btn').addEventListener('click', handleLoRaFrequencyChange);\n"
"\n"
"    // LoRa Sync Word 변경 버튼\n"
"    document.getElementById('lora-sync-save-btn').addEventListener('click', handleLoRaSyncWordChange);\n"
"\n"
"    // LoRa Sync Word 슬라이더 값 변경 시 표시 업데이트\n"
"    document.getElementById('lora-sync-input').addEventListener('input', (e) => {\n"
"        const value = parseInt(e.target.value);\n"
"        document.getElementById('lora-sync-value').textContent = '0x' + value.toString(16).toUpperCase().padStart(2, '0');\n"
"    });\n"
"\n"
"    // LoRa 설정 적용 버튼\n"
"    document.getElementById('lora-apply-btn').addEventListener('click', handleLoRaApply);\n"
"}\n"
"\n"
"// 설정 로드\n"
"async function loadConfig() {\n"
"    try {\n"
"        const response = await fetch(API.CONFIG);\n"
"        if (!response.ok) throw new Error('설정 로드 실패');\n"
"\n"
"        const config = await response.json();\n"
"\n"
"        // WiFi STA 설정\n"
"        document.getElementById('wifi-ssid').value = config.wifi_sta.ssid || '';\n"
"        document.getElementById('wifi-password').value = config.wifi_sta.password || '';\n"
"\n"
"        // Ethernet 설정\n"
"        document.getElementById('eth-dhcp').checked = config.eth.dhcp_enabled;\n"
"        document.getElementById('eth-ip').value = config.eth.static_ip || '';\n"
"        document.getElementById('eth-netmask').value = config.eth.static_netmask || '';\n"
"        document.getElementById('eth-gateway').value = config.eth.static_gateway || '';\n"
"\n"
"    } catch (error) {\n"
"        console.error('설정 로드 오류:', error);\n"
"        showMessage('설정을 불러오는데 실패했습니다.', 'error');\n"
"    }\n"
"}\n"
"\n"
"// 상태 업데이트\n"
"async function updateStatus() {\n"
"    try {\n"
"        const response = await fetch(API.STATUS);\n"
"        if (!response.ok) throw new Error('상태 조회 실패');\n"
"\n"
"        const status = await response.json();\n"
"\n"
"        // WiFi AP 상태\n"
"        updateWiFiAPStatus(status.wifi_ap, status.wifi_detail);\n"
"\n"
"        // WiFi STA 상태\n"
"        updateWiFiSTAStatus(status.wifi_sta, status.wifi_detail);\n"
"\n"
"        // Ethernet 상태\n"
"        updateEthStatus(status.ethernet, status.eth_detail);\n"
"\n"
"        // 스위처 상태 (switcher 필드가 있으면)\n"
"        if (status.switcher) {\n"
"            updateSwitcherStatus(status.switcher);\n"
"            // 개별 스위처 상태도 업데이트\n"
"            if (status.switcher.primary) {\n"
"                updateSwitcherItem(0, status.switcher.primary);\n"
"            }\n"
"            if (status.switcher.secondary) {\n"
"                updateSwitcherItem(1, status.switcher.secondary);\n"
"            }\n"
"        }\n"
"\n"
"        // LoRa 상태 (lora 필드가 있으면)\n"
"        if (status.lora) {\n"
"            updateLoRaStatusFromData(status.lora);\n"
"        }\n"
"\n"
"        // 전체 연결 상태\n"
"        updateConnectionBadge(status);\n"
"\n"
"    } catch (error) {\n"
"        console.error('상태 업데이트 오류:', error);\n"
"        document.getElementById('status-badge').textContent = '연결 끊김';\n"
"        document.getElementById('status-badge').className = 'badge';\n"
"    }\n"
"}\n"
"\n"
"// WiFi AP 상태 업데이트\n"
"function updateWiFiAPStatus(status, detail) {\n"
"    const html = `\n"
"        <div class=\"value\">${status.active ? '활성' : '비활성'}</div>\n"
"        ${status.active ? `\n"
"            <div class=\"label\">IP: ${status.ip}</div>\n"
"            <div class=\"label\">클라이언트: ${detail.ap_clients}개</div>\n"
"        ` : ''}\n"
"    `;\n"
"    document.getElementById('wifi-ap-status').innerHTML = html;\n"
"}\n"
"\n"
"// WiFi STA 상태 업데이트\n"
"function updateWiFiSTAStatus(status, detail) {\n"
"    const html = `\n"
"        <div class=\"value\">${status.connected ? '연결됨' : '연결 안됨'}</div>\n"
"        ${status.connected ? `\n"
"            <div class=\"label\">IP: ${status.ip}</div>\n"
"            <div class=\"label\">신호: ${detail.sta_rssi} dBm</div>\n"
"        ` : ''}\n"
"    `;\n"
"    document.getElementById('wifi-sta-status').innerHTML = html;\n"
"}\n"
"\n"
"// Ethernet 상태 업데이트\n"
"function updateEthStatus(status, detail) {\n"
"    const html = `\n"
"        <div class=\"value\">${status.active ? (status.connected ? '연결됨' : '연결 안됨') : '비활성'}</div>\n"
"        ${status.active && status.connected ? `\n"
"            <div class=\"label\">IP: ${status.ip}</div>\n"
"            <div class=\"label\">모드: ${detail.dhcp_mode ? 'DHCP' : 'Static'}</div>\n"
"            <div class=\"label\">MAC: ${detail.mac}</div>\n"
"        ` : (status.active ? '<div class=\"label\">케이블 확인</div>' : '<div class=\"label\">W5500 없음</div>')}\n"
"    `;\n"
"    document.getElementById('eth-status').innerHTML = html;\n"
"}\n"
"\n"
"// 스위처 상태 업데이트\n"
"function updateSwitcherStatus(switcher) {\n"
"    // 동작 모드\n"
"    const modeEl = document.getElementById('switcher-mode');\n"
"    if (modeEl) {\n"
"        if (!switcher.comm_initialized) {\n"
"            modeEl.textContent = '초기화 중...';\n"
"            modeEl.className = 'badge connecting';\n"
"        } else if (switcher.dual_mode) {\n"
"            modeEl.textContent = '듀얼 모드';\n"
"            modeEl.className = 'badge connected';\n"
"        } else {\n"
"            modeEl.textContent = '싱글 모드';\n"
"            modeEl.className = 'badge';\n"
"        }\n"
"    }\n"
"\n"
"    // 활성 스위처 개수\n"
"    const countEl = document.getElementById('switcher-active-count');\n"
"    if (countEl) {\n"
"        countEl.textContent = `${switcher.active_count}개`;\n"
"    }\n"
"\n"
"    // /api/status에는 program/preview만 있음\n"
"    // effective, offset 등은 /api/config/switchers에서 가져옴\n"
"\n"
"    // Primary 스위처\n"
"    updateSwitcherItem(0, switcher.primary);\n"
"\n"
"    // Secondary 스위처\n"
"    updateSwitcherItem(1, switcher.secondary);\n"
"}\n"
"\n"
"// 개별 스위처 상태 업데이트\n"
"function updateSwitcherItem(index, sw) {\n"
"    const badgeEl = document.getElementById(`sw${index}-status-badge`);\n"
"    const infoEl = document.getElementById(`sw${index}-connection-info`);\n"
"\n"
"    if (!badgeEl || !infoEl) return;\n"
"\n"
"    if (sw.connected) {\n"
"        badgeEl.textContent = '연결됨';\n"
"        badgeEl.className = 'badge connected';\n"
"\n"
"        const info = [];\n"
"        if (sw.product) info.push(`제품: ${sw.product}`);\n"
"        if (sw.num_cameras) info.push(`카메라: ${sw.num_cameras}개`);\n"
"        if (sw.program !== undefined) info.push(`PGM: ${sw.program}`);\n"
"        if (sw.preview !== undefined) info.push(`PVW: ${sw.preview}`);\n"
"        if (sw.offset !== undefined) info.push(`Offset: ${sw.offset}`);\n"
"        if (sw.limit !== undefined) info.push(`Limit: ${sw.limit === 0 ? '무제한' : sw.limit}`);\n"
"        if (sw.effective !== undefined) info.push(`Effective: ${sw.effective}`);\n"
"\n"
"        infoEl.innerHTML = `<div class=\"label\">${info.join(' | ')}</div>`;\n"
"    } else {\n"
"        badgeEl.textContent = '연결 안됨';\n"
"        badgeEl.className = 'badge';\n"
"        infoEl.innerHTML = '';\n"
"    }\n"
"}\n"
"\n"
"// 연결 상태 배지 업데이트\n"
"function updateConnectionBadge(status) {\n"
"    const badge = document.getElementById('status-badge');\n"
"\n"
"    if (status.wifi_sta.connected || status.ethernet.connected) {\n"
"        badge.textContent = '연결됨';\n"
"        badge.className = 'badge connected';\n"
"    } else {\n"
"        badge.textContent = 'AP 모드';\n"
"        badge.className = 'badge connecting';\n"
"    }\n"
"}\n"
"\n"
"// WiFi 스캔 처리\n"
"async function handleWiFiScan() {\n"
"    const btn = document.getElementById('wifi-scan-btn');\n"
"    const status = document.getElementById('wifi-scan-status');\n"
"    const resultsDiv = document.getElementById('wifi-scan-results');\n"
"\n"
"    try {\n"
"        btn.disabled = true;\n"
"        status.textContent = '검색 중...';\n"
"        resultsDiv.style.display = 'none';\n"
"\n"
"        const response = await fetch(API.WIFI_SCAN);\n"
"        if (!response.ok) throw new Error('WiFi 스캔 실패');\n"
"\n"
"        const data = await response.json();\n"
"\n"
"        if (data.count === 0) {\n"
"            status.textContent = '검색된 네트워크가 없습니다.';\n"
"            return;\n"
"        }\n"
"\n"
"        status.textContent = `${data.count}개 네트워크 발견`;\n"
"\n"
"        // 스캔 결과 표시\n"
"        resultsDiv.innerHTML = '';\n"
"        data.networks.forEach(network => {\n"
"            const networkItem = document.createElement('div');\n"
"            networkItem.className = 'wifi-network-item';\n"
"            networkItem.innerHTML = `\n"
"                <div class=\"network-info\">\n"
"                    <strong>${network.ssid}</strong>\n"
"                    <span class=\"network-auth\">${network.auth}</span>\n"
"                </div>\n"
"                <div class=\"network-details\">\n"
"                    <span>신호: ${network.rssi} dBm</span>\n"
"                    <span>채널: ${network.channel}</span>\n"
"                </div>\n"
"            `;\n"
"            networkItem.addEventListener('click', () => {\n"
"                document.getElementById('wifi-ssid').value = network.ssid;\n"
"                document.getElementById('wifi-password').focus();\n"
"            });\n"
"            resultsDiv.appendChild(networkItem);\n"
"        });\n"
"\n"
"        resultsDiv.style.display = 'block';\n"
"\n"
"    } catch (error) {\n"
"        console.error('WiFi 스캔 오류:', error);\n"
"        status.textContent = '스캔 실패';\n"
"        showMessage('WiFi 스캔에 실패했습니다.', 'error');\n"
"    } finally {\n"
"        btn.disabled = false;\n"
"    }\n"
"}\n"
"\n"
"// WiFi 설정 제출\n"
"async function handleWiFiSubmit(e) {\n"
"    e.preventDefault();\n"
"\n"
"    const formData = new FormData(e.target);\n"
"    const data = {\n"
"        ssid: formData.get('ssid'),\n"
"        password: formData.get('password')\n"
"    };\n"
"\n"
"    try {\n"
"        const response = await fetch(API.WIFI, {\n"
"            method: 'POST',\n"
"            headers: { 'Content-Type': 'application/json' },\n"
"            body: JSON.stringify(data)\n"
"        });\n"
"\n"
"        if (!response.ok) throw new Error('WiFi 설정 실패');\n"
"\n"
"        showMessage('WiFi 설정이 저장되고 재시작됩니다.', 'success');\n"
"\n"
"    } catch (error) {\n"
"        console.error('WiFi 설정 오류:', error);\n"
"        showMessage('WiFi 설정 저장에 실패했습니다.', 'error');\n"
"    }\n"
"}\n"
"\n"
"// Ethernet 설정 제출\n"
"async function handleEthSubmit(e) {\n"
"    e.preventDefault();\n"
"\n"
"    const formData = new FormData(e.target);\n"
"    const data = {\n"
"        dhcp_enabled: document.getElementById('eth-dhcp').checked,\n"
"        static_ip: formData.get('static_ip'),\n"
"        static_netmask: formData.get('static_netmask'),\n"
"        static_gateway: formData.get('static_gateway')\n"
"    };\n"
"\n"
"    try {\n"
"        const response = await fetch(API.ETH, {\n"
"            method: 'POST',\n"
"            headers: { 'Content-Type': 'application/json' },\n"
"            body: JSON.stringify(data)\n"
"        });\n"
"\n"
"        if (!response.ok) throw new Error('Ethernet 설정 실패');\n"
"\n"
"        showMessage('Ethernet 설정이 저장되었습니다. 재시작 후 적용됩니다.', 'success');\n"
"\n"
"    } catch (error) {\n"
"        console.error('Ethernet 설정 오류:', error);\n"
"        showMessage('Ethernet 설정 저장에 실패했습니다.', 'error');\n"
"    }\n"
"}\n"
"\n"
"// 모드 변경 처리\n"
"async function handleModeChange() {\n"
"    const mode = document.getElementById('switcher-mode-select').value;\n"
"    const isDual = (mode === 'dual');\n"
"\n"
"    try {\n"
"        // 단순히 dual_mode 플래그만 변경\n"
"        await fetch(API.MODE, {\n"
"            method: 'POST',\n"
"            headers: { 'Content-Type': 'application/json' },\n"
"            body: JSON.stringify({ dual_mode: isDual })\n"
"        });\n"
"\n"
"        showMessage(`${isDual ? '듀얼' : '싱글'} 모드로 설정되었습니다. 스위처 연결 재시작이 필요합니다.`, 'success');\n"
"\n"
"        // 설정 다시 로드\n"
"        setTimeout(() => {\n"
"            loadSwitcherConfig();\n"
"        }, 500);\n"
"\n"
"    } catch (error) {\n"
"        console.error('모드 변경 오류:', error);\n"
"        showMessage('모드 변경에 실패했습니다.', 'error');\n"
"    }\n"
"}\n"
"\n"
"// 스위처 연결 재시작\n"
"async function handleSwitcherRestart() {\n"
"    try {\n"
"        showMessage('스위처 연결을 재시작합니다...', 'info');\n"
"\n"
"        const response = await fetch(API.SWITCHER_RESTART, { method: 'POST' });\n"
"        if (!response.ok) throw new Error('스위처 재시작 실패');\n"
"\n"
"        // 연결 대기\n"
"        const result = await waitForSwitcherConnection(10);\n"
"        showMessage(result.message, result.success ? 'success' : 'error');\n"
"\n"
"    } catch (error) {\n"
"        console.error('스위처 재시작 오류:', error);\n"
"        showMessage('스위처 재시작에 실패했습니다.', 'error');\n"
"    }\n"
"}\n"
"\n"
"// 시스템 재시작\n"
"async function handleRestart() {\n"
"    if (!confirm('시스템을 재시작하시겠습니까?')) return;\n"
"\n"
"    try {\n"
"        const response = await fetch(API.RESTART, { method: 'POST' });\n"
"        if (!response.ok) throw new Error('재시작 실패');\n"
"\n"
"        clearInterval(updateTimer);\n"
"        showMessage('시스템을 재시작합니다...', 'success');\n"
"\n"
"        // 20초 후 페이지 새로고침\n"
"        setTimeout(() => {\n"
"            window.location.reload();\n"
"        }, 20000);\n"
"\n"
"    } catch (error) {\n"
"        console.error('재시작 오류:', error);\n"
"        showMessage('재시작에 실패했습니다.', 'error');\n"
"    }\n"
"}\n"
"\n"
"\n"
"// 스위처 설정 로드\n"
"async function loadSwitcherConfig() {\n"
"    try {\n"
"        const response = await fetch(API.SWITCHERS);\n"
"        if (!response.ok) throw new Error('스위처 설정 로드 실패');\n"
"\n"
"        const data = await response.json();\n"
"        const switchers = data.switchers;\n"
"\n"
"        // switcherData 초기화 및 설정 저장\n"
"        switcherData = {\n"
"            switchers: switchers,  // 전체 스위처 설정 저장\n"
"            primary: { limit: 0, offset: 0, effective: 0 },\n"
"            secondary: { limit: 0, offset: 0, effective: 0 }\n"
"        };\n"
"\n"
"        // 모드 선택 설정 (dual_mode 플래그 사용)\n"
"        const isDualMode = data.dual_mode || false;\n"
"        document.getElementById('switcher-mode-select').value = isDualMode ? 'dual' : 'single';\n"
"\n"
"        // 매핑 데이터 저장\n"
"        switchers.forEach(sw => {\n"
"            if (sw.index === 0) {\n"
"                switcherData.primary.limit = sw.camera_limit || 0;\n"
"                switcherData.primary.offset = sw.camera_offset || 0;\n"
"                switcherData.primary.effective = sw.effective_count || 0;\n"
"            } else if (sw.index === 1) {\n"
"                switcherData.secondary.limit = sw.camera_limit || 0;\n"
"                switcherData.secondary.offset = sw.camera_offset || 0;\n"
"                switcherData.secondary.effective = sw.effective_count || 0;\n"
"            }\n"
"        });\n"
"\n"
"        // Secondary 시작 위치 설정 (서버에서 받은 offset 사용)\n"
"        const secondaryOffset = switcherData.secondary.offset || 0;\n"
"        secondaryStartPos = secondaryOffset + 1;\n"
"\n"
"        // 비주얼 매핑 UI 생성\n"
"        renderCameraMapping();\n"
"\n"
"    } catch (error) {\n"
"        console.error('스위처 설정 로드 오류:', error);\n"
"        showMessage('스위처 설정을 불러오는데 실패했습니다.', 'error');\n"
"    }\n"
"}\n"
"\n"
"// 스위처 재시작 후 연결 대기\n"
"async function waitForSwitcherConnection(countdown = 10) {\n"
"    return new Promise((resolve) => {\n"
"        let timeLeft = countdown;\n"
"        const checkInterval = 1000; // 1초마다 체크\n"
"\n"
"        const checkConnection = async () => {\n"
"            try {\n"
"                const response = await fetch(API.STATUS);\n"
"                if (response.ok) {\n"
"                    const status = await response.json();\n"
"\n"
"                    if (status.switcher) {\n"
"                        const isDualMode = status.switcher.dual_mode;\n"
"                        const primaryConnected = status.switcher.primary?.connected || false;\n"
"                        const secondaryConnected = status.switcher.secondary?.connected || false;\n"
"\n"
"                        // 연결 상태 체크\n"
"                        if (isDualMode) {\n"
"                            // 듀얼 모드: 둘 다 연결되어야 함\n"
"                            if (primaryConnected && secondaryConnected) {\n"
"                                resolve({ success: true, message: '모든 스위처가 연결되었습니다.' });\n"
"                                return;\n"
"                            }\n"
"                        } else {\n"
"                            // 싱글 모드: Primary만 연결되면 됨\n"
"                            if (primaryConnected) {\n"
"                                resolve({ success: true, message: '스위처가 연결되었습니다.' });\n"
"                                return;\n"
"                            }\n"
"                        }\n"
"\n"
"                        // 시간 초과 체크\n"
"                        if (timeLeft <= 0) {\n"
"                            let failMessage = '';\n"
"                            if (isDualMode) {\n"
"                                if (!primaryConnected && !secondaryConnected) {\n"
"                                    failMessage = '두 스위처 모두 연결에 실패했습니다.';\n"
"                                } else if (!primaryConnected) {\n"
"                                    failMessage = 'Primary 스위처 연결에 실패했습니다.';\n"
"                                } else if (!secondaryConnected) {\n"
"                                    failMessage = 'Secondary 스위처 연결에 실패했습니다.';\n"
"                                }\n"
"                            } else {\n"
"                                failMessage = 'Primary 스위처 연결에 실패했습니다.';\n"
"                            }\n"
"                            resolve({ success: false, message: failMessage });\n"
"                            return;\n"
"                        }\n"
"\n"
"                        // 카운트다운 메시지 업데이트\n"
"                        showMessage(`스위처 재시작 중... (${timeLeft}초)`, 'info');\n"
"                        timeLeft--;\n"
"                        setTimeout(checkConnection, checkInterval);\n"
"                    }\n"
"                }\n"
"            } catch (error) {\n"
"                if (timeLeft <= 0) {\n"
"                    resolve({ success: false, message: '스위처 연결 상태를 확인할 수 없습니다.' });\n"
"                } else {\n"
"                    timeLeft--;\n"
"                    setTimeout(checkConnection, checkInterval);\n"
"                }\n"
"            }\n"
"        };\n"
"\n"
"        checkConnection();\n"
"    });\n"
"}\n"
"\n"
"// 스위처 설정 제출\n"
"async function handleSwitcherSubmit(e) {\n"
"    e.preventDefault();\n"
"\n"
"    const form = e.target;\n"
"    const index = parseInt(form.dataset.index);\n"
"    const formData = new FormData(form);\n"
"\n"
"    const data = {\n"
"        index: index,\n"
"        type: parseInt(formData.get('type')),\n"
"        interface: parseInt(formData.get('interface')),\n"
"        ip: formData.get('ip'),\n"
"        password: formData.get('password')\n"
"        // port는 서버에서 타입에 따라 자동 설정됨\n"
"    };\n"
"\n"
"    try {\n"
"        const response = await fetch(API.SWITCHER, {\n"
"            method: 'POST',\n"
"            headers: { 'Content-Type': 'application/json' },\n"
"            body: JSON.stringify(data)\n"
"        });\n"
"\n"
"        if (!response.ok) throw new Error('스위처 설정 실패');\n"
"\n"
"        showMessage(`스위처 ${index === 0 ? 'Primary' : 'Secondary'} 설정이 저장되었습니다. 스위처 연결 재시작이 필요합니다.`, 'success');\n"
"\n"
"        // 설정 다시 로드\n"
"        setTimeout(() => {\n"
"            loadSwitcherConfig();\n"
"        }, 500);\n"
"\n"
"    } catch (error) {\n"
"        console.error('스위처 설정 오류:', error);\n"
"        showMessage('스위처 설정 저장에 실패했습니다.', 'error');\n"
"    }\n"
"}\n"
"\n"
"// 카메라 제한 저장\n"
"async function saveCameraLimit(index, limit) {\n"
"    const data = {\n"
"        index: index,\n"
"        camera_limit: limit,\n"
"        camera_offset: index === 0 ? 0 : (secondaryStartPos - 1)\n"
"    };\n"
"\n"
"    const response = await fetch(API.SWITCHER_MAPPING, {\n"
"        method: 'POST',\n"
"        headers: { 'Content-Type': 'application/json' },\n"
"        body: JSON.stringify(data)\n"
"    });\n"
"\n"
"    if (!response.ok) throw new Error('카메라 제한 저장 실패');\n"
"}\n"
"\n"
"// Health 상태 업데이트\n"
"async function updateHealth() {\n"
"    try {\n"
"        const response = await fetch(API.HEALTH);\n"
"        if (!response.ok) throw new Error('Health API 요청 실패');\n"
"\n"
"        const data = await response.json();\n"
"\n"
"        // 전체 상태\n"
"        const overallEl = document.getElementById('health-overall');\n"
"        overallEl.className = 'health-value';\n"
"        overallEl.classList.add(`status-${data.status}`);\n"
"        switch(data.status) {\n"
"            case 'ok':\n"
"                overallEl.textContent = '✓ 정상';\n"
"                break;\n"
"            case 'warning':\n"
"                overallEl.textContent = '⚠ 경고';\n"
"                break;\n"
"            case 'critical':\n"
"                overallEl.textContent = '✗ 위험';\n"
"                break;\n"
"            default:\n"
"                overallEl.textContent = '알 수 없음';\n"
"        }\n"
"\n"
"        // 업타임\n"
"        const uptimeEl = document.getElementById('health-uptime');\n"
"        const uptime = formatUptime(data.uptime_sec);\n"
"        uptimeEl.textContent = uptime;\n"
"        uptimeEl.className = 'health-value';\n"
"\n"
"        // 전압\n"
"        const voltageEl = document.getElementById('health-voltage');\n"
"        if (data.voltage && data.voltage.volts !== undefined) {\n"
"            voltageEl.textContent = data.voltage.volts.toFixed(2) + ' V';\n"
"            voltageEl.className = 'health-value';\n"
"            voltageEl.classList.add(`status-${data.voltage.status}`);\n"
"        } else {\n"
"            voltageEl.textContent = '사용 불가';\n"
"            voltageEl.className = 'health-value status-unavailable';\n"
"        }\n"
"\n"
"        // 배터리\n"
"        const batteryEl = document.getElementById('health-battery');\n"
"        if (data.voltage && data.voltage.percentage !== undefined) {\n"
"            batteryEl.textContent = data.voltage.percentage + ' %';\n"
"            batteryEl.className = 'health-value';\n"
"            batteryEl.classList.add(`status-${data.voltage.status}`);\n"
"        } else {\n"
"            batteryEl.textContent = '사용 불가';\n"
"            batteryEl.className = 'health-value status-unavailable';\n"
"        }\n"
"\n"
"        // 메모리\n"
"        const memoryEl = document.getElementById('health-memory');\n"
"        if (data.memory) {\n"
"            const freeKB = (data.memory.free_heap_bytes / 1024).toFixed(1);\n"
"            memoryEl.textContent = freeKB + ' KB';\n"
"            memoryEl.className = 'health-value';\n"
"            memoryEl.classList.add(`status-${data.memory.status}`);\n"
"        } else {\n"
"            memoryEl.textContent = '사용 불가';\n"
"            memoryEl.className = 'health-value status-unavailable';\n"
"        }\n"
"\n"
"        // 온도\n"
"        const tempEl = document.getElementById('health-temperature');\n"
"        if (data.temperature && data.temperature.celsius !== undefined) {\n"
"            tempEl.textContent = data.temperature.celsius.toFixed(1) + ' °C';\n"
"            tempEl.className = 'health-value';\n"
"            tempEl.classList.add(`status-${data.temperature.status}`);\n"
"        } else {\n"
"            tempEl.textContent = '사용 불가';\n"
"            tempEl.className = 'health-value status-unavailable';\n"
"        }\n"
"\n"
"        // CPU\n"
"        const cpuEl = document.getElementById('health-cpu');\n"
"        if (data.cpu && data.cpu.core0_usage_percent !== undefined && data.cpu.core1_usage_percent !== undefined) {\n"
"            const avgUsage = Math.round((data.cpu.core0_usage_percent + data.cpu.core1_usage_percent) / 2);\n"
"            cpuEl.textContent = avgUsage + ' %';\n"
"            cpuEl.title = `Core0: ${data.cpu.core0_usage_percent}% | Core1: ${data.cpu.core1_usage_percent}%`;\n"
"            cpuEl.className = 'health-value';\n"
"            cpuEl.classList.add(`status-${data.cpu.status}`);\n"
"        } else {\n"
"            cpuEl.textContent = '사용 불가';\n"
"            cpuEl.className = 'health-value status-unavailable';\n"
"        }\n"
"\n"
"    } catch (error) {\n"
"        console.error('Health 업데이트 실패:', error);\n"
"    }\n"
"}\n"
"\n"
"// 업타임 포맷팅 (초 -> 일시분초)\n"
"function formatUptime(seconds) {\n"
"    const days = Math.floor(seconds / 86400);\n"
"    const hours = Math.floor((seconds % 86400) / 3600);\n"
"    const minutes = Math.floor((seconds % 3600) / 60);\n"
"    const secs = Math.floor(seconds % 60);\n"
"\n"
"    if (days > 0) {\n"
"        return `${days}일 ${hours}시간`;\n"
"    } else if (hours > 0) {\n"
"        return `${hours}시간 ${minutes}분`;\n"
"    } else if (minutes > 0) {\n"
"        return `${minutes}분 ${secs}초`;\n"
"    } else {\n"
"        return `${secs}초`;\n"
"    }\n"
"}\n"
"\n"
"// 비주얼 카메라 매핑 렌더링\n"
"function renderCameraMapping() {\n"
"    const container = document.getElementById('camera-mapping-buttons');\n"
"    container.innerHTML = '';\n"
"\n"
"    // API 데이터 로드 전\n"
"    if (!switcherData) {\n"
"        container.innerHTML = '<p style=\"color: #6b7280;\">Loading...</p>';\n"
"        return;\n"
"    }\n"
"\n"
"    // effective 값 사용 (사용자 설정값과 스위처 실제값 중 작은 값)\n"
"    const primary = switcherData.primary.effective || 0;\n"
"    const secondary = switcherData.secondary.effective || 0;\n"
"\n"
"    if (primary === 0 && secondary === 0) {\n"
"        container.innerHTML = '<p style=\"color: #6b7280;\">No switcher configured.</p>';\n"
"        return;\n"
"    }\n"
"\n"
"    // Secondary 시작 위치는 전역 변수 사용 (클릭으로 변경 가능)\n"
"    // 초기 로드 시에만 offset 값으로 설정\n"
"    // secondaryStartPos는 handleCameraClick에서 변경됨\n"
"\n"
"    // total 계산: 항상 20채널 표시\n"
"    const total = 20;\n"
"\n"
"    // 검증: Primary + Secondary + Other = 20 (Secondary가 Primary를 덮어씀)\n"
"    let primaryCount = 0, secondaryCount = 0, otherCount = 0;\n"
"    for (let i = 1; i <= total; i++) {\n"
"        // Secondary 영역\n"
"        if (secondary > 0 && i >= secondaryStartPos && i < secondaryStartPos + secondary) {\n"
"            secondaryCount++;\n"
"        }\n"
"        // Primary 영역 (Secondary와 겹치지 않는 부분만)\n"
"        else if (i <= primary && !(secondary > 0 && i >= secondaryStartPos && i < secondaryStartPos + secondary)) {\n"
"            primaryCount++;\n"
"        }\n"
"        // 나머지\n"
"        else {\n"
"            otherCount++;\n"
"        }\n"
"    }\n"
"    console.log(`[Mapping] Primary:${primaryCount} + Secondary:${secondaryCount} + Other:${otherCount} = ${primaryCount + secondaryCount + otherCount}`);\n"
"\n"
"    // 버튼 생성\n"
"    for (let i = 1; i <= total; i++) {\n"
"        const btn = document.createElement('button');\n"
"        btn.className = 'camera-btn';\n"
"        btn.textContent = i;\n"
"        btn.type = 'button';\n"
"\n"
"        // Combined Tally 기준으로 effective 영역 표시\n"
"        // Secondary가 있으면 offset 위치부터 Secondary로 덮어씀\n"
"        const secondaryEnd = secondaryStartPos + secondary;\n"
"\n"
"        if (secondary > 0 && i >= secondaryStartPos && i < secondaryEnd) {\n"
"            // Secondary 영역 (파란색)\n"
"            btn.classList.add('secondary');\n"
"        }\n"
"        else if (i <= primary && (secondary === 0 || i < secondaryStartPos)) {\n"
"            // Primary 영역 (Secondary 시작 위치 이전만 표시)\n"
"            // Secondary가 Primary 영역으로 들어오면 Secondary 시작 위치 이후의 Primary는 제거\n"
"            btn.classList.add('primary');\n"
"        }\n"
"        else if (secondary > 0) {\n"
"            // Secondary가 있을 때: effective 범위 밖의 선택 가능 영역\n"
"            btn.classList.add('selectable-secondary');\n"
"        }\n"
"\n"
"        // Secondary 시작 위치 버튼 강조 표시\n"
"        if (secondary > 0 && i === secondaryStartPos) {\n"
"            btn.classList.add('selected');\n"
"        }\n"
"\n"
"        // 모든 버튼 클릭 가능\n"
"        if (secondary > 0) {\n"
"            btn.classList.add('clickable');\n"
"            btn.addEventListener('click', () => handleCameraClick(i));\n"
"        }\n"
"\n"
"        container.appendChild(btn);\n"
"    }\n"
"\n"
"    // Secondary 시작 위치 표시\n"
"    document.getElementById('secondary-start-pos').textContent =\n"
"        secondary > 0 ? secondaryStartPos : '-';\n"
"}\n"
"\n"
"// 카메라 버튼 클릭 핸들러\n"
"function handleCameraClick(position) {\n"
"    secondaryStartPos = position;\n"
"    renderCameraMapping();\n"
"}\n"
"\n"
"// 매핑 저장\n"
"async function handleMappingSave() {\n"
"    try {\n"
"        // Secondary 오프셋 저장 (offset = position - 1)\n"
"        const data = {\n"
"            index: 1,\n"
"            camera_limit: switcherData.secondary.limit,\n"
"            camera_offset: secondaryStartPos - 1\n"
"        };\n"
"\n"
"        const response = await fetch(API.SWITCHER_MAPPING, {\n"
"            method: 'POST',\n"
"            headers: { 'Content-Type': 'application/json' },\n"
"            body: JSON.stringify(data)\n"
"        });\n"
"\n"
"        if (!response.ok) throw new Error('매핑 저장 실패');\n"
"\n"
"        showMessage('카메라 매핑이 저장되었습니다.', 'success');\n"
"\n"
"        // 설정 다시 로드\n"
"        setTimeout(() => {\n"
"            loadSwitcherConfig();\n"
"        }, 500);\n"
"\n"
"    } catch (error) {\n"
"        console.error('매핑 저장 오류:', error);\n"
"        showMessage('매핑 저장에 실패했습니다.', 'error');\n"
"    }\n"
"}\n"
"\n"
"// 토스트 메시지 표시\n"
"function showMessage(text, type = 'success') {\n"
"    const container = document.getElementById('toast-container');\n"
"\n"
"    const toast = document.createElement('div');\n"
"    toast.className = `toast ${type}`;\n"
"    toast.textContent = text;\n"
"\n"
"    container.appendChild(toast);\n"
"\n"
"    // 3초 후 제거\n"
"    setTimeout(() => {\n"
"        toast.classList.add('hiding');\n"
"        setTimeout(() => {\n"
"            toast.remove();\n"
"        }, 300); // 애니메이션 시간\n"
"    }, 3000);\n"
"}\n"
"\n"
"// ============================================================================\n"
"// 모달 제어\n"
"// ============================================================================\n"
"\n"
"/**\n"
" * 스위처 설정 모달 열기\n"
" * @param {number} index - 스위처 인덱스 (0: Primary, 1: Secondary)\n"
" */\n"
"function openSwitcherModal(index) {\n"
"    const modal = document.getElementById('switcher-modal');\n"
"    const title = document.getElementById('modal-title');\n"
"    const modalIndex = document.getElementById('modal-index');\n"
"    const typeSelect = document.getElementById('modal-type');\n"
"\n"
"    // 모달 제목 설정\n"
"    title.textContent = index === 0 ? 'Primary Switcher 설정' : 'Secondary Switcher 설정';\n"
"    modalIndex.value = index;\n"
"\n"
"    // 현재 설정 불러오기\n"
"    if (switcherData && switcherData.switchers && switcherData.switchers[index]) {\n"
"        const config = switcherData.switchers[index];\n"
"        document.getElementById('modal-type').value = config.type;\n"
"        document.getElementById('modal-interface').value = config.interface;\n"
"        document.getElementById('modal-ip').value = config.ip;\n"
"        document.getElementById('modal-password').value = config.password || '';\n"
"        document.getElementById('modal-camera-limit').value = config.camera_limit || 0;\n"
"    } else {\n"
"        // 기본값 설정\n"
"        document.getElementById('modal-type').value = '1';  // ATEM\n"
"        document.getElementById('modal-interface').value = '2';  // Ethernet\n"
"        document.getElementById('modal-ip').value = '';\n"
"        document.getElementById('modal-password').value = '';\n"
"        document.getElementById('modal-camera-limit').value = 0;\n"
"    }\n"
"\n"
"    // 타입 변경 이벤트 리스너 등록\n"
"    typeSelect.onchange = updateModalFields;\n"
"\n"
"    // 초기 필드 상태 설정\n"
"    updateModalFields();\n"
"\n"
"    // 모달 표시\n"
"    modal.classList.add('show');\n"
"\n"
"    // 이벤트 리스너 등록 (중복 방지를 위해 기존 리스너 제거 후 추가)\n"
"    const saveBtn = document.getElementById('modal-save-btn');\n"
"    saveBtn.onclick = handleModalSave;\n"
"}\n"
"\n"
"/**\n"
" * 스위처 타입에 따라 모달 필드 표시/숨김\n"
" */\n"
"function updateModalFields() {\n"
"    const type = parseInt(document.getElementById('modal-type').value);\n"
"    const passwordGroup = document.getElementById('modal-password-group');\n"
"\n"
"    // OBS(3)인 경우만 비밀번호 필드 표시\n"
"    if (type === 3) {\n"
"        passwordGroup.style.display = 'block';\n"
"    } else {\n"
"        passwordGroup.style.display = 'none';\n"
"        document.getElementById('modal-password').value = '';  // 값 초기화\n"
"    }\n"
"}\n"
"\n"
"/**\n"
" * 스위처 설정 모달 닫기\n"
" */\n"
"function closeSwitcherModal() {\n"
"    const modal = document.getElementById('switcher-modal');\n"
"    modal.classList.remove('show');\n"
"}\n"
"\n"
"/**\n"
" * 모달 저장 버튼 핸들러\n"
" */\n"
"async function handleModalSave() {\n"
"    const index = parseInt(document.getElementById('modal-index').value);\n"
"    const type = parseInt(document.getElementById('modal-type').value);\n"
"    const interfaceType = parseInt(document.getElementById('modal-interface').value);\n"
"    const ip = document.getElementById('modal-ip').value;\n"
"    const password = document.getElementById('modal-password').value;\n"
"    const cameraLimit = parseInt(document.getElementById('modal-camera-limit').value) || 0;\n"
"\n"
"    // 유효성 검사\n"
"    if (!ip) {\n"
"        showMessage('IP 주소를 입력해주세요.', 'error');\n"
"        return;\n"
"    }\n"
"\n"
"    try {\n"
"        const response = await fetch(API.SWITCHER, {\n"
"            method: 'POST',\n"
"            headers: {\n"
"                'Content-Type': 'application/json'\n"
"            },\n"
"            body: JSON.stringify({\n"
"                index: index,\n"
"                type: type,\n"
"                interface: interfaceType,\n"
"                ip: ip,\n"
"                password: password,\n"
"                camera_limit: cameraLimit\n"
"            })\n"
"        });\n"
"\n"
"        if (!response.ok) throw new Error('저장 실패');\n"
"\n"
"        showMessage(`스위처 ${index === 0 ? 'Primary' : 'Secondary'} 설정이 저장되었습니다. 스위처 연결 재시작이 필요합니다.`, 'success');\n"
"\n"
"        // 모달 닫기\n"
"        closeSwitcherModal();\n"
"\n"
"        // 설정 새로고침\n"
"        setTimeout(() => {\n"
"            loadSwitcherConfig();\n"
"        }, 500);\n"
"\n"
"    } catch (error) {\n"
"        console.error('저장 오류:', error);\n"
"        showMessage('설정 저장에 실패했습니다.', 'error');\n"
"    }\n"
"}\n"
"\n"
"// 모달 외부 클릭 시 닫기\n"
"window.addEventListener('click', (event) => {\n"
"    const modal = document.getElementById('switcher-modal');\n"
"    if (event.target === modal) {\n"
"        closeSwitcherModal();\n"
"    }\n"
"});\n"
"\n"
"// ============================================================================\n"
"// LoRa 관련 함수\n"
"// ============================================================================\n"
"\n"
"/**\n"
" * LoRa 상태 업데이트\n"
" */\n"
"/**\n"
" * LoRa 상태 업데이트 (데이터로부터)\n"
" */\n"
"function updateLoRaStatusFromData(status) {\n"
"    // 칩 정보\n"
"    const chipBadge = document.getElementById('lora-chip');\n"
"    chipBadge.textContent = status.chip_name || 'Unknown';\n"
"    chipBadge.className = status.initialized ? 'badge badge-success' : 'badge badge-error';\n"
"\n"
"    // 주파수\n"
"    document.getElementById('lora-frequency').textContent =\n"
"        status.frequency ? `${status.frequency.toFixed(1)} MHz` : '-';\n"
"\n"
"    // API에서 받은 주파수 범위 사용\n"
"    const minFreq = status.freq_min || 850;\n"
"    const maxFreq = status.freq_max || 930;\n"
"    const rangeText = `${minFreq.toFixed(0)}~${maxFreq.toFixed(0)} MHz (${status.chip_name})`;\n"
"\n"
"    // 스캔 범위 표시\n"
"    document.getElementById('scan-range-display').textContent = rangeText;\n"
"\n"
"    // 주파수 입력 필드 설정\n"
"    const freqInput = document.getElementById('lora-freq-input');\n"
"    freqInput.min = minFreq;\n"
"    freqInput.max = maxFreq;\n"
"    // 처음 한 번만 값 설정 (이후 업데이트 안 함)\n"
"    if (!freqInput.dataset.initialized) {\n"
"        freqInput.value = status.frequency || ((minFreq + maxFreq) / 2);\n"
"        freqInput.dataset.initialized = 'true';\n"
"    }\n"
"\n"
"    // 주파수 범위 힌트\n"
"    document.getElementById('freq-range-hint').textContent = `지원 범위: ${rangeText}`;\n"
"\n"
"    // Sync Word 슬라이더 설정\n"
"    const syncInput = document.getElementById('lora-sync-input');\n"
"    const syncValue = document.getElementById('lora-sync-value');\n"
"    // 처음 한 번만 값 설정 (이후 업데이트 안 함)\n"
"    if (!syncInput.dataset.initialized) {\n"
"        const syncWordValue = status.sync_word !== undefined ? status.sync_word : 0x12;\n"
"        syncInput.value = syncWordValue;\n"
"        syncValue.textContent = '0x' + syncWordValue.toString(16).toUpperCase().padStart(2, '0');\n"
"        syncInput.dataset.initialized = 'true';\n"
"    }\n"
"\n"
"    // 전역 변수에 저장 (스캔에서 사용)\n"
"    window.loraFreqRange = { min: minFreq, max: maxFreq };\n"
"}\n"
"\n"
"/**\n"
" * LoRa 상태 업데이트 (API 호출) - 초기 로드용\n"
" */\n"
"async function updateLoRaStatus() {\n"
"    try {\n"
"        const response = await fetch(API.STATUS);\n"
"        if (!response.ok) throw new Error('상태 조회 실패');\n"
"\n"
"        const data = await response.json();\n"
"        if (data.lora) {\n"
"            updateLoRaStatusFromData(data.lora);\n"
"        }\n"
"\n"
"    } catch (error) {\n"
"        console.error('LoRa 상태 업데이트 오류:', error);\n"
"    }\n"
"}\n"
"\n"
"/**\n"
" * LoRa 주파수 스캔\n"
" */\n"
"async function handleLoRaScan() {\n"
"    // 주파수 범위는 칩 타입에 따라 자동 설정\n"
"    if (!window.loraFreqRange) {\n"
"        showMessage('LoRa 상태를 먼저 확인해주세요.', 'error');\n"
"        return;\n"
"    }\n"
"\n"
"    const startFreq = window.loraFreqRange.min;\n"
"    const endFreq = window.loraFreqRange.max;\n"
"    const step = 1.0;  // 고정값: 1MHz\n"
"\n"
"    const channelCount = Math.floor((endFreq - startFreq) / step) + 1;\n"
"    const estimatedTime = (channelCount * 0.1).toFixed(1);\n"
"\n"
"    const scanBtn = document.getElementById('lora-scan-btn');\n"
"    const scanStatus = document.getElementById('lora-scan-status');\n"
"\n"
"    scanBtn.disabled = true;\n"
"    scanStatus.textContent = `스캔 중... (약 ${estimatedTime}초 소요, ${channelCount}개 채널)`;\n"
"\n"
"    try {\n"
"        const response = await fetch(`${API.LORA_SCAN}?start=${startFreq}&end=${endFreq}`);\n"
"        if (!response.ok) throw new Error('스캔 실패');\n"
"\n"
"        const result = await response.json();\n"
"\n"
"        // 결과 표시\n"
"        displayScanResults(result.channels);\n"
"        scanStatus.textContent = `완료: ${result.count}개 채널 스캔됨`;\n"
"        showMessage(`주파수 스캔 완료: ${result.count}개 채널`, 'success');\n"
"\n"
"    } catch (error) {\n"
"        console.error('스캔 오류:', error);\n"
"        const errorMsg = error.message || '알 수 없는 오류';\n"
"        scanStatus.textContent = `스캔 실패: ${errorMsg}`;\n"
"        showMessage(`주파수 스캔 실패: ${errorMsg}`, 'error');\n"
"    } finally {\n"
"        scanBtn.disabled = false;\n"
"    }\n"
"}\n"
"\n"
"/**\n"
" * 스캔 결과 시각화\n"
" */\n"
"function displayScanResults(channels) {\n"
"    const resultsDiv = document.getElementById('lora-scan-results');\n"
"    const chartDiv = document.getElementById('lora-scan-chart');\n"
"\n"
"    if (!channels || channels.length === 0) {\n"
"        resultsDiv.style.display = 'none';\n"
"        return;\n"
"    }\n"
"\n"
"    resultsDiv.style.display = 'block';\n"
"\n"
"    // 차트 생성 (간단한 바 차트) - 10개만 보이고 스크롤\n"
"    let html = '<div style=\"display: flex; flex-direction: column; gap: 5px; max-height: 300px; overflow-y: auto;\">';\n"
"\n"
"    channels.forEach(ch => {\n"
"        const rssi = ch.rssi;\n"
"\n"
"        // RSSI를 0~100 스케일로 변환 (-100 dBm = 100%, -50 dBm = 0%, -100 이하는 100%)\n"
"        const rssiPercent = Math.max(0, Math.min(100, ((-50 - rssi) / 50) * 100));\n"
"\n"
"        // -80 dBm 이하 = 녹색, 이상 = 빨간색\n"
"        const color = (rssi < -80) ? '#4CAF50' : '#f44336';\n"
"\n"
"        html += `\n"
"            <div style=\"display: flex; align-items: center; gap: 10px;\">\n"
"                <div style=\"width: 80px; text-align: right; font-size: 12px;\">${ch.frequency.toFixed(1)} MHz</div>\n"
"                <div style=\"flex: 1; background: #eee; height: 20px; border-radius: 3px; overflow: visible; position: relative; cursor: pointer;\"\n"
"                     onclick=\"document.getElementById('lora-freq-input').value = ${ch.frequency.toFixed(1)};\">\n"
"                    <div style=\"width: ${rssiPercent}%; height: 100%; background: ${color};\"></div>\n"
"                    <div style=\"position: absolute; right: 5px; top: 50%; transform: translateY(-50%); font-size: 10px; color: #666; pointer-events: none;\">\n"
"                        ${rssi.toFixed(1)}\n"
"                    </div>\n"
"                </div>\n"
"            </div>\n"
"        `;\n"
"    });\n"
"\n"
"    html += '</div>';\n"
"    chartDiv.innerHTML = html;\n"
"}\n"
"\n"
"/**\n"
" * LoRa 주파수 변경\n"
" */\n"
"async function handleLoRaFrequencyChange() {\n"
"    const frequency = parseFloat(document.getElementById('lora-freq-input').value);\n"
"    const syncWord = parseInt(document.getElementById('lora-sync-input').value);\n"
"\n"
"    if (isNaN(frequency)) {\n"
"        showMessage('올바른 주파수를 입력해주세요.', 'error');\n"
"        return;\n"
"    }\n"
"\n"
"    // 칩 타입에 따른 범위 체크\n"
"    if (window.loraFreqRange) {\n"
"        if (frequency < window.loraFreqRange.min || frequency > window.loraFreqRange.max) {\n"
"            showMessage(`주파수는 ${window.loraFreqRange.min}~${window.loraFreqRange.max} MHz 범위여야 합니다.`, 'error');\n"
"            return;\n"
"        }\n"
"    }\n"
"\n"
"    try {\n"
"        const response = await fetch(API.LORA_CONFIG, {\n"
"            method: 'POST',\n"
"            headers: { 'Content-Type': 'application/json' },\n"
"            body: JSON.stringify({ frequency: frequency, sync_word: syncWord })\n"
"        });\n"
"\n"
"        if (!response.ok) throw new Error('주파수 임시 저장 실패');\n"
"\n"
"        // 대기 중 표시\n"
"        document.getElementById('freq-pending-badge').style.display = 'inline';\n"
"        showMessage(`주파수 ${frequency.toFixed(1)} MHz 임시 저장됨 (아래 \"설정 적용하기\" 버튼 클릭 필요)`, 'success');\n"
"\n"
"    } catch (error) {\n"
"        console.error('주파수 임시 저장 오류:', error);\n"
"        showMessage('주파수 임시 저장에 실패했습니다.', 'error');\n"
"    }\n"
"}\n"
"\n"
"/**\n"
" * LoRa Sync Word 변경\n"
" */\n"
"async function handleLoRaSyncWordChange() {\n"
"    const frequency = parseFloat(document.getElementById('lora-freq-input').value);\n"
"    const syncWord = parseInt(document.getElementById('lora-sync-input').value);\n"
"\n"
"    try {\n"
"        const response = await fetch(API.LORA_CONFIG, {\n"
"            method: 'POST',\n"
"            headers: { 'Content-Type': 'application/json' },\n"
"            body: JSON.stringify({ frequency: frequency, sync_word: syncWord })\n"
"        });\n"
"\n"
"        if (!response.ok) throw new Error('Sync Word 임시 저장 실패');\n"
"\n"
"        // 대기 중 표시\n"
"        document.getElementById('sync-pending-badge').style.display = 'inline';\n"
"        showMessage(`Sync Word 0x${syncWord.toString(16).toUpperCase()} 임시 저장됨 (아래 \"설정 적용하기\" 버튼 클릭 필요)`, 'success');\n"
"\n"
"    } catch (error) {\n"
"        console.error('Sync Word 임시 저장 오류:', error);\n"
"        showMessage('Sync Word 임시 저장에 실패했습니다.', 'error');\n"
"    }\n"
"}\n"
"\n"
"/**\n"
" * LoRa 설정 적용 (3회 송신 + 1초 대기 + TX 변경)\n"
" */\n"
"async function handleLoRaApply() {\n"
"    const applyBtn = document.getElementById('lora-apply-btn');\n"
"    const statusDiv = document.getElementById('lora-apply-status');\n"
"\n"
"    applyBtn.disabled = true;\n"
"    statusDiv.style.color = '#0066cc';\n"
"    statusDiv.innerHTML = '📡 RX 장치에 알림 전송 중... (1/3)';\n"
"\n"
"    try {\n"
"        // 실제 API 호출 (백엔드에서 전체 프로세스 수행)\n"
"        const response = await fetch('/api/lora/apply', {\n"
"            method: 'POST'\n"
"        });\n"
"\n"
"        if (!response.ok) throw new Error('설정 적용 실패');\n"
"\n"
"        // 진행 상황 표시 (백엔드에서 처리 중)\n"
"        await new Promise(r => setTimeout(r, 1000));\n"
"        statusDiv.innerHTML = '📡 RX 장치에 알림 전송 중... (2/3)';\n"
"\n"
"        await new Promise(r => setTimeout(r, 1000));\n"
"        statusDiv.innerHTML = '📡 RX 장치에 알림 전송 중... (3/3)';\n"
"\n"
"        await new Promise(r => setTimeout(r, 1000));\n"
"        statusDiv.innerHTML = '⏳ RX 장치 설정 변경 대기 중...';\n"
"\n"
"        await new Promise(r => setTimeout(r, 1000));\n"
"        statusDiv.innerHTML = '🔄 TX 설정 변경 중...';\n"
"\n"
"        await new Promise(r => setTimeout(r, 500));\n"
"\n"
"        // 성공\n"
"        statusDiv.style.color = '#28a745';\n"
"        statusDiv.innerHTML = '✅ 설정 적용 완료!';\n"
"\n"
"        // 대기 중 표시 제거\n"
"        document.getElementById('freq-pending-badge').style.display = 'none';\n"
"        document.getElementById('sync-pending-badge').style.display = 'none';\n"
"\n"
"        showMessage('LoRa 설정이 적용되었습니다', 'success');\n"
"\n"
"        // 상태 새로고침\n"
"        setTimeout(() => {\n"
"            updateStatus();\n"
"            statusDiv.innerHTML = '';\n"
"        }, 2000);\n"
"\n"
"    } catch (error) {\n"
"        statusDiv.style.color = '#dc3545';\n"
"        statusDiv.innerHTML = '❌ 설정 적용 실패';\n"
"        showMessage('설정 적용에 실패했습니다', 'error');\n"
"        console.error('설정 적용 오류:', error);\n"
"    } finally {\n"
"        applyBtn.disabled = false;\n"
"    }\n"
"}\n"
"\n";

const size_t app_js_len = sizeof(app_js) - 1;

